export const SET_LEVEL = 'SET_LEVEL';

export const SET_CUTSCENE = 'SET_CUTSCENE';

export const SET_AVAILABLE_CHARACTERS = 'SET_AVAILABLE_CHARACTERS';
export const SET_CURRENT_CHARACTERS = 'SET_CURRENT_CHARACTERS';